# Generated by Django 3.1.4 on 2021-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaction', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, max_length=100)),
            ],
        ),
    ]
