# Generated by Django 3.1.4 on 2021-01-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='loaction',
            new_name='location',
        ),
    ]
